"""FreeFlyer script generation — creates .MissionPlan files from BEPI parameters.

FreeFlyer (a.i. solutions) uses its own procedural scripting language.
This module generates FreeFlyer scripts for:
- Orbit propagation with reporting
- Ground station contact analysis
- Eclipse analysis
- Maneuver planning
- Orbit maintenance
"""
from datetime import datetime
import textwrap

from bepi.integrations.gmat import (
    SpacecraftParams, OrbitParams, PropagationConfig, GroundStation,
    COMMON_GROUND_STATIONS,
)
from .celestial_bodies import get_body

# FreeFlyer gravity model names per body
_FF_GRAVITY_MODELS: dict[str, tuple[str, int, int]] = {
    "Earth": ("EGM96", 20, 20),
    "Moon": ("LP165P", 20, 20),
    "Mars": ("Mars50c", 20, 20),
    "Venus": ("MGNP180U", 20, 20),
}


def generate_propagation_script(
    sc: SpacecraftParams | None = None,
    orbit: OrbitParams | None = None,
    config: PropagationConfig | None = None,
    ground_stations: list[GroundStation] | None = None,
) -> str:
    sc = sc or SpacecraftParams()
    orbit = orbit or OrbitParams()
    config = config or PropagationConfig()
    gs_list = ground_stations or []

    # FreeFlyer epoch format: "DD Mon YYYY HH:MM:SS.SSS"
    ff_epoch = orbit.epoch  # Already in compatible format

    force_block = _force_model(config, orbit.body)

    gs_block = ""
    gs_contact_block = ""
    for gs in gs_list:
        gs_block += textwrap.dedent(f"""\
            GroundStation {gs.name};
            {gs.name}.Latitude = {gs.lat_deg};
            {gs.name}.Longitude = {gs.lon_deg};
            {gs.name}.Altitude = {gs.alt_m / 1000:.3f};
            {gs.name}.MinimumElevationAngle = {gs.min_elevation_deg};

        """)
        gs_contact_block += textwrap.dedent(f"""\
            ContactAnalysis contact_{gs.name};
            contact_{gs.name}.Spacecraft = sc;
            contact_{gs.name}.GroundStation = {gs.name};
            contact_{gs.name}.SearchInterval = prop.Stepsize;

        """)

    report_vars = f"""
            Report.Epoch = sc.Epoch;
            Report.SMA = sc.A;
            Report.Altitude = sc.Altitude;
            Report.Latitude = sc.Latitude;
            Report.Longitude = sc.Longitude;
            Report.ECC = sc.E;
            Report.INC = sc.I;"""

    script = textwrap.dedent(f"""\
        // ============================================================
        // BEPI-SAT FreeFlyer Mission Plan — Auto-generated by BEPI
        // Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
        // ============================================================

        // ---- Spacecraft Definition ----
        Spacecraft sc;
        sc.Epoch = "{ff_epoch}";
        sc.A = {orbit.sma_km};
        sc.E = {orbit.ecc};
        sc.I = {orbit.inc_deg};
        sc.RAAN = {orbit.raan_deg};
        sc.W = {orbit.aop_deg};
        sc.TA = {orbit.ta_deg};
        sc.DryMass = {sc.dry_mass_kg};
        sc.FuelMass = {sc.fuel_mass_kg};
        sc.Cd = {sc.cd};
        sc.Cr = {sc.cr};
        sc.DragArea = {sc.drag_area_m2};
        sc.SRPArea = {sc.srp_area_m2};

        // ---- Ground Stations ----
        {gs_block}
        // ---- Force Model & Propagator ----
        {force_block}
        Propagator prop;
        prop.ForceModel = fm;
        prop.Stepsize = {config.step_size_s};
        prop.Type = "RungeKutta89";

        // ---- Contact Analysis ----
        {gs_contact_block}
        // ---- Eclipse Analysis ----
        EclipseAnalysis eclipse;
        eclipse.Spacecraft = sc;
        eclipse.EclipsingBodies = {{"{orbit.body}"}};

        // ---- Reporting ----
        Variable Report;
        OutputFile OrbitReport("OrbitReport.csv");
        OrbitReport.Headers = {{"Epoch", "SMA_km", "Alt_km", "Lat_deg", "Lon_deg", "ECC", "INC_deg"}};

        // ---- Mission Sequence ----
        While (sc.ElapsedTime < {config.duration_days * 86400});
            Step sc;
            {report_vars}
            OrbitReport.Write(Report);
        End;

        // ---- Output Eclipse Report ----
        OutputFile EclipseReport("EclipseReport.csv");
        For i = 0 to eclipse.NumberOfEvents - 1;
            EclipseReport.Write(eclipse.StartTime(i), eclipse.StopTime(i), eclipse.Duration(i));
        End;

        Report "Propagation complete. Duration: {config.duration_days} days";
    """)
    return script


def generate_maneuver_script(
    sc: SpacecraftParams | None = None,
    orbit: OrbitParams | None = None,
    delta_v_ms: float = 1.0,
    direction: str = "velocity",
) -> str:
    sc = sc or SpacecraftParams()
    orbit = orbit or OrbitParams()

    dv_kms = delta_v_ms / 1000.0

    if direction == "velocity":
        dv_line = f"burn.DeltaV = [{dv_kms}, 0, 0];"
    elif direction == "normal":
        dv_line = f"burn.DeltaV = [0, {dv_kms}, 0];"
    else:
        dv_line = f"burn.DeltaV = [0, 0, {dv_kms}];"

    script = textwrap.dedent(f"""\
        // ============================================================
        // BEPI-SAT FreeFlyer Maneuver — Auto-generated by BEPI
        // Delta-V: {delta_v_ms:.3f} m/s ({direction})
        // Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
        // ============================================================

        Spacecraft sc;
        sc.Epoch = "{orbit.epoch}";
        sc.A = {orbit.sma_km};
        sc.E = {orbit.ecc};
        sc.I = {orbit.inc_deg};
        sc.RAAN = {orbit.raan_deg};
        sc.W = {orbit.aop_deg};
        sc.TA = {orbit.ta_deg};
        sc.DryMass = {sc.dry_mass_kg};
        sc.FuelMass = {sc.fuel_mass_kg};

        ImpulsiveBurn burn;
        burn.Frame = "VNB";
        {dv_line}

        ForceModel fm;
        fm.CentralBody = "{orbit.body}";
        fm.GravityDegree = 10;
        fm.GravityOrder = 10;
        fm.AtmosphericDrag = {"On" if get_body(orbit.body).has_atmosphere and orbit.body == "Earth" else "Off"};
        fm.SolarRadiationPressure = On;

        Propagator prop;
        prop.ForceModel = fm;

        OutputFile ManeuverReport("ManeuverReport.csv");
        ManeuverReport.Headers = {{"Epoch", "SMA_km", "Alt_km", "Mass_kg"}};

        // Pre-burn coast
        While (sc.ElapsedTime < 1800);
            Step sc;
            ManeuverReport.Write(sc.Epoch, sc.A, sc.Altitude, sc.Mass);
        End;

        // Execute burn
        Report "Pre-burn SMA: " + sc.A.ToString() + " km";
        Maneuver sc(burn);
        Report "Post-burn SMA: " + sc.A.ToString() + " km";
        Report "Fuel remaining: " + sc.FuelMass.ToString() + " kg";

        // Post-burn propagation
        While (sc.ElapsedTime < 86400);
            Step sc;
            ManeuverReport.Write(sc.Epoch, sc.A, sc.Altitude, sc.Mass);
        End;
    """)
    return script


def generate_stationkeeping_script(
    sc: SpacecraftParams | None = None,
    orbit: OrbitParams | None = None,
    target_alt_km: float = 550.0,
    tolerance_km: float = 5.0,
    sim_days: float = 30.0,
) -> str:
    sc = sc or SpacecraftParams()
    orbit = orbit or OrbitParams()

    script = textwrap.dedent(f"""\
        // ============================================================
        // BEPI-SAT FreeFlyer Station-Keeping — Auto-generated by BEPI
        // Target: {target_alt_km} km +/- {tolerance_km} km
        // Simulation: {sim_days} days
        // Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
        // ============================================================

        Spacecraft sc;
        sc.Epoch = "{orbit.epoch}";
        sc.A = {orbit.sma_km};
        sc.E = {orbit.ecc};
        sc.I = {orbit.inc_deg};
        sc.RAAN = {orbit.raan_deg};
        sc.W = {orbit.aop_deg};
        sc.TA = {orbit.ta_deg};
        sc.DryMass = {sc.dry_mass_kg};
        sc.FuelMass = {sc.fuel_mass_kg};
        sc.Cd = {sc.cd};
        sc.DragArea = {sc.drag_area_m2};

        ImpulsiveBurn sk_burn;
        sk_burn.Frame = "VNB";
        sk_burn.DeltaV = [0.001, 0, 0];  // Small prograde burn

        ForceModel fm;
        fm.CentralBody = "{orbit.body}";
        fm.GravityDegree = 20;
        fm.GravityOrder = 20;
        fm.AtmosphericDrag = {"On" if get_body(orbit.body).has_atmosphere and orbit.body == "Earth" else "Off"};
        fm.SolarRadiationPressure = On;
        fm.F107 = 150;
        fm.F107A = 150;

        Propagator prop;
        prop.ForceModel = fm;

        Variable dv_total = 0;
        Variable n_burns = 0;
        Variable sim_end = {sim_days * 86400};

        OutputFile SKReport("StationKeepingReport.csv");
        SKReport.Headers = {{"Epoch", "Alt_km", "DV_total_ms", "N_burns", "Mass_kg"}};

        While (sc.ElapsedTime < sim_end);
            Step sc;

            // Check altitude threshold
            If (sc.Altitude < {target_alt_km - tolerance_km});
                Maneuver sc(sk_burn);
                dv_total = dv_total + 1.0;  // m/s per burn
                n_burns = n_burns + 1;
                Report "SK burn #" + n_burns.ToString() + " at alt " + sc.Altitude.ToString() + " km";
            End;

            SKReport.Write(sc.Epoch, sc.Altitude, dv_total, n_burns, sc.Mass);
        End;

        Report "=== Station-Keeping Summary ===";
        Report "Total burns: " + n_burns.ToString();
        Report "Total delta-V: " + dv_total.ToString() + " m/s";
        Report "Final fuel mass: " + sc.FuelMass.ToString() + " kg";
    """)
    return script


def _force_model(config: PropagationConfig, body: str = "Earth") -> str:
    cb = get_body(body)

    if config.force_model == "two_body":
        return textwrap.dedent(f"""\
            ForceModel fm;
            fm.CentralBody = "{body}";
            fm.GravityDegree = 0;
            fm.GravityOrder = 0;
        """)
    elif config.force_model == "j2":
        return textwrap.dedent(f"""\
            ForceModel fm;
            fm.CentralBody = "{body}";
            fm.GravityDegree = 2;
            fm.GravityOrder = 0;
        """)
    else:
        grav = _FF_GRAVITY_MODELS.get(body)
        if grav is None:
            # Unknown body — two-body with SRP
            return textwrap.dedent(f"""\
                ForceModel fm;
                fm.CentralBody = "{body}";
                fm.GravityDegree = 0;
                fm.GravityOrder = 0;
                fm.SolarRadiationPressure = On;
                fm.SRPFlux = 1367;
            """)

        model_name, deg, order = grav
        lines = [
            "ForceModel fm;",
            f'fm.CentralBody = "{body}";',
            f"fm.GravityDegree = {deg};",
            f"fm.GravityOrder = {order};",
            f'fm.GravityModel = "{model_name}";',
        ]

        if cb.has_atmosphere and body == "Earth":
            lines += [
                "fm.AtmosphericDrag = On;",
                'fm.DragModel = "NRLMSISE00";',
                "fm.F107 = 150;",
                "fm.F107A = 150;",
                "fm.Kp = 3;",
            ]
        elif cb.has_atmosphere and body == "Mars":
            lines += [
                "fm.AtmosphericDrag = On;",
                'fm.DragModel = "MarsGRAM";',
            ]

        lines += [
            "fm.SolarRadiationPressure = On;",
            "fm.SRPFlux = 1367;",
        ]

        if body == "Earth":
            lines.append('fm.ThirdBodies = {"Sun", "Moon"};')
        elif body == "Moon":
            lines.append('fm.ThirdBodies = {"Sun", "Earth"};')
        elif cb.parent == "Sun":
            lines.append('fm.ThirdBodies = {"Sun"};')
        else:
            lines.append(f'fm.ThirdBodies = {{"Sun", "{cb.parent}"}};')

        return "\n".join(lines) + "\n"
