"""Total Mission script generation — single script spanning all mission phases.

Generates unified GMAT, FreeFlyer, and MATLAB scripts that cover the complete
mission profile: departure orbit, escape, heliocentric transfer, capture,
destination orbit — with body transitions and ΔV annotations.
"""
from __future__ import annotations

import math
from .celestial_bodies import get_body, BODIES
from .mission_phases import MissionProfile, MissionPhase, PhaseType
from .gmat import SpacecraftParams, OrbitParams, PropagationConfig


_AU_KM = 1.496e8


def _phase_orbit(phase: MissionPhase) -> OrbitParams:
    fp = phase.full_orbital_params
    b = get_body(phase.body)
    alt = fp.get("alt_km", 550)
    return OrbitParams(
        sma_km=b.radius_km + alt,
        ecc=fp.get("ecc", 0.001),
        inc_deg=fp.get("inc_deg", 0.0),
        raan_deg=fp.get("raan_deg", 0.0),
        aop_deg=fp.get("aop_deg", 0.0),
        ta_deg=0.0,
        body=phase.body,
    )


def _is_helio(pt: PhaseType) -> bool:
    return pt in (PhaseType.TRANSFER, PhaseType.ESCAPE, PhaseType.FLYBY)


# ---------------------------------------------------------------------------
# GMAT
# ---------------------------------------------------------------------------

def generate_total_mission_gmat(profile: MissionProfile, sc: SpacecraftParams | None = None) -> str:
    sc = sc or SpacecraftParams()
    lines = [
        f"%% GMAT — Total Mission Script: {profile.name}",
        "%% Auto-generated by BEPI — contains all mission phases",
        "%% WARNING: this is a preliminary script; verify force models before use",
        "",
    ]

    # Spacecraft
    lines += [
        f"Create Spacecraft {sc.name};",
        f"{sc.name}.DryMass = {sc.dry_mass_kg};",
        f"{sc.name}.Cd = {sc.cd};",
        f"{sc.name}.Cr = {sc.cr};",
        f"{sc.name}.DragArea = {sc.drag_area_m2};",
        f"{sc.name}.SRPArea = {sc.srp_area_m2};",
        "",
    ]

    # Per-phase blocks
    for i, phase in enumerate(profile.phases):
        tag = f"Phase{i}"
        orb = _phase_orbit(phase)
        body = phase.body
        gmat_body = "Luna" if body == "Moon" else body
        coord = f"{gmat_body}MJ2000Eq"

        if _is_helio(phase.phase_type):
            body = "Sun"
            gmat_body = "Sun"
            coord = "SunMJ2000Eq"
            b_dep = get_body(phase.body)
            orb = OrbitParams(
                sma_km=b_dep.sma_au * _AU_KM,
                ecc=0.0,
                inc_deg=0.0,
                body="Sun",
            )

        dur_s = phase.duration_days * 86400

        lines += [
            f"%% --- {phase.name} ({phase.phase_type.value}) around {body} ---",
            f"Create ForceModel fm_{tag};",
            f"fm_{tag}.CentralBody = {gmat_body};",
            f"fm_{tag}.PointMasses = {{{gmat_body}}};",
            "",
            f"Create Propagator prop_{tag};",
            f"prop_{tag}.FM = fm_{tag};",
            f"prop_{tag}.Type = RungeKutta89;",
            f"prop_{tag}.InitialStepSize = 60;",
            "",
            f"{sc.name}.CoordinateSystem = {coord};",
            f"{sc.name}.SMA = {orb.sma_km:.4f};",
            f"{sc.name}.ECC = {orb.ecc};",
            f"{sc.name}.INC = {orb.inc_deg};",
            f"{sc.name}.RAAN = {orb.raan_deg};",
            f"{sc.name}.AOP = {orb.aop_deg};",
            f"{sc.name}.TA = {orb.ta_deg};",
            "",
        ]

        if phase.delta_v_ms > 0:
            dv_kms = phase.delta_v_ms / 1000.0
            lines += [
                f"Create ImpulsiveBurn burn_{tag};",
                f"burn_{tag}.CoordinateSystem = {coord};",
                f"burn_{tag}.Element1 = {dv_kms:.6f};  % km/s ({phase.delta_v_ms:.1f} m/s)",
                "",
                f"Maneuver burn_{tag}({sc.name});",
            ]

        lines += [
            f"Propagate prop_{tag}({sc.name}) {{{sc.name}.ElapsedSecs = {dur_s:.0f}}};",
            "",
        ]

    lines.append(f"%% End of mission: {profile.name}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# FreeFlyer
# ---------------------------------------------------------------------------

def generate_total_mission_freeflyer(profile: MissionProfile, sc: SpacecraftParams | None = None) -> str:
    sc = sc or SpacecraftParams()
    lines = [
        f"// FreeFlyer — Total Mission Script: {profile.name}",
        "// Auto-generated by BEPI",
        "",
        f"Spacecraft {sc.name};",
        f"{sc.name}.DryMass = {sc.dry_mass_kg};",
        f"{sc.name}.Cd = {sc.cd};",
        f"{sc.name}.Cr = {sc.cr};",
        "",
    ]

    for i, phase in enumerate(profile.phases):
        tag = f"Phase{i}"
        orb = _phase_orbit(phase)
        body = phase.body
        dur_s = phase.duration_days * 86400

        if _is_helio(phase.phase_type):
            body = "Sun"
            b_dep = get_body(phase.body)
            orb = OrbitParams(
                sma_km=b_dep.sma_au * _AU_KM,
                ecc=0.0,
                inc_deg=0.0,
                body="Sun",
            )

        lines += [
            f"// --- {phase.name} ({phase.phase_type.value}) around {body} ---",
            f"{sc.name}.CentralBody = \"{body}\";",
            f"{sc.name}.A = {orb.sma_km:.4f};",
            f"{sc.name}.E = {orb.ecc};",
            f"{sc.name}.I = {orb.inc_deg};",
            f"{sc.name}.RAAN = {orb.raan_deg};",
            f"{sc.name}.W = {orb.aop_deg};",
            f"{sc.name}.TA = {orb.ta_deg};",
            "",
        ]

        if phase.delta_v_ms > 0:
            dv_kms = phase.delta_v_ms / 1000.0
            lines += [
                f"ImpulsiveBurn burn_{tag};",
                f"burn_{tag}.DeltaV = [{dv_kms:.6f}, 0, 0];  // km/s",
                f"{sc.name}.Maneuver(burn_{tag});",
                "",
            ]

        lines += [
            f"While ({sc.name}.ElapsedTime < {dur_s:.0f});",
            f"    Step {sc.name};",
            f"End;",
            "",
        ]

    lines.append(f"// End of mission: {profile.name}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# MATLAB
# ---------------------------------------------------------------------------

def generate_total_mission_matlab(profile: MissionProfile, sc: SpacecraftParams | None = None) -> str:
    sc = sc or SpacecraftParams()
    lines = [
        f"%% BEPI — Total Mission MATLAB Script: {profile.name}",
        "%% Auto-generated — requires Aerospace Toolbox",
        "",
        f"m_dry = {sc.dry_mass_kg};  % kg",
        f"Cd = {sc.cd};",
        "Isp = 220;  % s (hydrazine default)",
        "g0 = 9.80665;  % m/s^2",
        "total_dv = 0;  % m/s cumulative",
        "",
    ]

    for i, phase in enumerate(profile.phases):
        tag = f"phase{i}"
        body = phase.body
        b = get_body(body)
        orb = _phase_orbit(phase)
        dur_s = phase.duration_days * 86400

        if _is_helio(phase.phase_type):
            body = "Sun"
            b = get_body("Sun")
            b_dep = get_body(phase.body)
            sma = b_dep.sma_au * _AU_KM
        else:
            sma = orb.sma_km

        period_s = 2 * math.pi * (sma ** 3 / b.mu_km3s2) ** 0.5

        lines += [
            f"%% --- {phase.name} ({phase.phase_type.value}) around {body} ---",
            f"mu_{tag} = {b.mu_km3s2:.4f};  % km^3/s^2",
            f"sma_{tag} = {sma:.1f};  % km",
            f"T_{tag} = 2*pi*sqrt(sma_{tag}^3/mu_{tag});  % period: {period_s/60:.1f} min",
            f"dur_{tag} = {dur_s:.0f};  % s ({phase.duration_days:.1f} days)",
            "",
        ]

        if phase.delta_v_ms > 0:
            dv = phase.delta_v_ms
            lines += [
                f"dv_{tag} = {dv:.1f};  % m/s",
                f"total_dv = total_dv + dv_{tag};",
                f"fprintf('Phase {i} ({phase.name}): dV = %.1f m/s\\n', dv_{tag});",
                "",
            ]

        lines += [
            f"n_orbits_{tag} = ceil(dur_{tag} / T_{tag});",
            f"fprintf('{phase.name}: %d orbits over %.1f days around {body}\\n', n_orbits_{tag}, dur_{tag}/86400);",
            "",
        ]

    lines += [
        "%% --- Mission Summary ---",
        "fprintf('\\n=== TOTAL MISSION SUMMARY ===\\n');",
        f"fprintf('Mission: {profile.name}\\n');",
        f"fprintf('Phases: {len(profile.phases)}\\n');",
        "fprintf('Total delta-V: %.1f m/s\\n', total_dv);",
        "",
        "%% Propellant estimate (Tsiolkovsky)",
        "mass_ratio = exp(total_dv / (Isp * g0));",
        "m_prop = m_dry * (mass_ratio - 1);",
        "fprintf('Estimated propellant: %.2f kg (Isp=%d s)\\n', m_prop, Isp);",
    ]

    return "\n".join(lines)
