"""NAIF SPICE kernel generation — creates text kernel files from BEPI mission parameters.

Generates FK, IK, SCLK, SPK (mkspk input), CK (msopck input), PCK, MK, and DSK (mkdsk input)
kernel files for spacecraft missions without requiring spiceypy or SPICE toolkit at generation time.
"""
from dataclasses import dataclass, field
from datetime import datetime, timedelta
import math
import textwrap


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class InstrumentDef:
    name: str
    abbrev: str  # e.g. "CAM1"
    naif_id_offset: int  # added to sc_id, e.g. -100 -> -100100
    fov_shape: str = "CIRCLE"  # CIRCLE | RECTANGLE | POLYGON
    fov_half_angle_deg: float = 5.0
    fov_half_angle_cross_deg: float | None = None  # for RECTANGLE
    boresight: tuple[float, float, float] = (0.0, 0.0, 1.0)
    frame_angles_deg: tuple[float, float, float] = (0.0, 0.0, 0.0)  # relative to SC body
    frame_axes: tuple[int, int, int] = (1, 2, 3)


@dataclass
class BodyDef:
    name: str
    naif_id: int
    radii_km: tuple[float, float, float]  # equatorial_a, equatorial_b, polar
    pole_ra_deg: float = 0.0
    pole_dec_deg: float = 90.0
    pm_deg: float = 0.0
    pm_rate_deg_per_day: float = 0.0


@dataclass
class OrbitState:
    epoch: str  # UTC string "2027-06-01T12:00:00"
    x_km: float = 0.0
    y_km: float = 0.0
    z_km: float = 0.0
    vx_km_s: float = 0.0
    vy_km_s: float = 0.0
    vz_km_s: float = 0.0


@dataclass
class MissionKernelParams:
    mission_name: str = "BEPISAT"
    sc_naif_id: int = -100000
    sc_body_axes: str = "XYZ"  # body frame axis labels
    instruments: list[InstrumentDef] = field(default_factory=list)
    orbit_sma_km: float = 6928.14
    orbit_ecc: float = 0.001
    orbit_inc_deg: float = 97.6
    orbit_raan_deg: float = 0.0
    orbit_aop_deg: float = 0.0
    orbit_ta_deg: float = 0.0
    central_body: str = "EARTH"
    central_body_mu_km3s2: float = 398600.4418
    epoch: str = "2027-06-01T12:00:00"
    mission_start: str = "2027-06-01T00:00:00"
    attitude_mode: str = "NADIR"  # NADIR | INERTIAL | SUN_POINTING
    tick_rate_hz: float = 1.0
    extra_bodies: list[BodyDef] = field(default_factory=list)
    kernel_dir: str = "kernels"


# ---------------------------------------------------------------------------
# Standard body constants
# ---------------------------------------------------------------------------

STANDARD_BODIES: list[BodyDef] = [
    BodyDef("EARTH", 399, (6378.1366, 6378.1366, 6356.7519),
            0.0, 90.0, 190.147, 360.9856235),
    BodyDef("MOON", 301, (1737.4, 1737.4, 1737.4),
            269.9949, 66.5392, 38.3213, 13.17635815),
    BodyDef("MARS", 499, (3396.19, 3396.19, 3376.20),
            317.68143, 52.88650, 176.630, 350.89198226),
    BodyDef("JUPITER", 599, (71492.0, 71492.0, 66854.0),
            268.056595, 64.495303, 284.95, 870.5360000),
]


# ---------------------------------------------------------------------------
# FK — Frame Kernel
# ---------------------------------------------------------------------------

def generate_fk(mission_name: str, sc_id: int, body_axes: str,
                instruments: list[InstrumentDef] | None = None) -> str:
    frame_name = f"{mission_name}_SC_BODY"
    frame_id = sc_id * 1000

    lines = [
        "KPL/FK",
        "",
        "\\begintext",
        f"  Frame kernel for {mission_name}",
        f"  SC NAIF ID: {sc_id}",
        f"  Generated by BEPI on {datetime.utcnow().isoformat()}",
        "",
        "\\begindata",
        "",
        f"  FRAME_{frame_name}            = {frame_id}",
        f"  FRAME_{frame_id}_NAME         = '{frame_name}'",
        f"  FRAME_{frame_id}_CLASS        = 3",
        f"  FRAME_{frame_id}_CLASS_ID     = {frame_id}",
        f"  FRAME_{frame_id}_CENTER       = {sc_id}",
        f"  CK_{frame_id}_SCLK            = {sc_id}",
        f"  CK_{frame_id}_SPK             = {sc_id}",
        "",
        f"  OBJECT_{sc_id}_FRAME          = '{frame_name}'",
        "",
    ]

    if instruments:
        for inst in instruments:
            inst_id = sc_id - inst.naif_id_offset
            inst_frame = f"{mission_name}_{inst.abbrev}"
            inst_frame_id = inst_id * 1000
            a1, a2, a3 = inst.frame_angles_deg
            ax1, ax2, ax3 = inst.frame_axes

            lines += [
                f"  FRAME_{inst_frame}            = {inst_frame_id}",
                f"  FRAME_{inst_frame_id}_NAME     = '{inst_frame}'",
                f"  FRAME_{inst_frame_id}_CLASS    = 4",
                f"  FRAME_{inst_frame_id}_CLASS_ID = {inst_frame_id}",
                f"  FRAME_{inst_frame_id}_CENTER   = {inst_id}",
                f"  TKFRAME_{inst_frame_id}_RELATIVE = '{frame_name}'",
                f"  TKFRAME_{inst_frame_id}_SPEC     = 'ANGLES'",
                f"  TKFRAME_{inst_frame_id}_ANGLES   = ( {a1}, {a2}, {a3} )",
                f"  TKFRAME_{inst_frame_id}_AXES     = ( {ax1}, {ax2}, {ax3} )",
                f"  TKFRAME_{inst_frame_id}_UNITS    = 'DEGREES'",
                "",
                f"  NAIF_BODY_NAME += ( '{mission_name}_{inst.name}', '{inst_id}' )",
                f"  NAIF_BODY_CODE += ( {inst_id} )",
                "",
            ]

    lines += [
        f"  NAIF_BODY_NAME += ( '{mission_name}' )",
        f"  NAIF_BODY_CODE += ( {sc_id} )",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# IK — Instrument Kernel
# ---------------------------------------------------------------------------

def _circle_boundary_vectors(half_angle_deg: float, boresight: tuple[float, float, float],
                             n_pts: int = 4) -> list[tuple[float, float, float]]:
    ha = math.radians(half_angle_deg)
    # Construct orthonormal basis with boresight as Z
    bx, by, bz = boresight
    # Pick an arbitrary vector not parallel to boresight
    if abs(bx) < 0.9:
        ref = (1.0, 0.0, 0.0)
    else:
        ref = (0.0, 1.0, 0.0)
    # cross product boresight x ref -> u
    ux = by * ref[2] - bz * ref[1]
    uy = bz * ref[0] - bx * ref[2]
    uz = bx * ref[1] - by * ref[0]
    norm = math.sqrt(ux**2 + uy**2 + uz**2)
    ux, uy, uz = ux / norm, uy / norm, uz / norm
    # v = boresight x u
    vx = by * uz - bz * uy
    vy = bz * ux - bx * uz
    vz = bx * uy - by * ux

    vectors = []
    for i in range(n_pts):
        theta = 2 * math.pi * i / n_pts
        dx = math.sin(ha) * (math.cos(theta) * ux + math.sin(theta) * vx) + math.cos(ha) * bx
        dy = math.sin(ha) * (math.cos(theta) * uy + math.sin(theta) * vy) + math.cos(ha) * by
        dz = math.sin(ha) * (math.cos(theta) * uz + math.sin(theta) * vz) + math.cos(ha) * bz
        vectors.append((dx, dy, dz))
    return vectors


def _rect_boundary_vectors(ha_along: float, ha_cross: float,
                           boresight: tuple[float, float, float]) -> list[tuple[float, float, float]]:
    a = math.radians(ha_along)
    c = math.radians(ha_cross)
    bx, by, bz = boresight
    corners = [
        (math.tan(a), math.tan(c), 1.0),
        (-math.tan(a), math.tan(c), 1.0),
        (-math.tan(a), -math.tan(c), 1.0),
        (math.tan(a), -math.tan(c), 1.0),
    ]
    result = []
    for cx, cy, cz in corners:
        norm = math.sqrt(cx**2 + cy**2 + cz**2)
        result.append((cx / norm, cy / norm, cz / norm))
    return result


def generate_ik(instrument_name: str, fov_shape: str, fov_half_angle_deg: float,
                boresight: tuple[float, float, float], sc_id: int,
                naif_id_offset: int = 100,
                fov_half_angle_cross_deg: float | None = None) -> str:
    inst_id = sc_id - naif_id_offset

    if fov_shape.upper() == "CIRCLE":
        boundary = _circle_boundary_vectors(fov_half_angle_deg, boresight, 4)
        shape_str = "CIRCLE"
    elif fov_shape.upper() == "RECTANGLE":
        cross = fov_half_angle_cross_deg or fov_half_angle_deg
        boundary = _rect_boundary_vectors(fov_half_angle_deg, cross, boresight)
        shape_str = "RECTANGLE"
    else:
        boundary = _circle_boundary_vectors(fov_half_angle_deg, boresight, 4)
        shape_str = "CIRCLE"

    lines = [
        "KPL/IK",
        "",
        "\\begintext",
        f"  Instrument kernel for {instrument_name}",
        f"  NAIF ID: {inst_id}",
        f"  FOV: {shape_str} {fov_half_angle_deg} deg half-angle",
        "",
        "\\begindata",
        "",
        f"  INS{inst_id}_FOV_SHAPE        = '{shape_str}'",
        f"  INS{inst_id}_FOV_FRAME        = '{instrument_name}'",
        f"  INS{inst_id}_BORESIGHT        = ( {boresight[0]:.6f}, {boresight[1]:.6f}, {boresight[2]:.6f} )",
        f"  INS{inst_id}_FOV_CLASS_SPEC   = 'ANGLES'",
        f"  INS{inst_id}_FOV_REF_ANGLE    = {fov_half_angle_deg}",
        f"  INS{inst_id}_FOV_ANGLE_UNITS  = 'DEGREES'",
        "",
    ]

    # Boundary vectors
    ref_vec = boundary[0] if boundary else (1.0, 0.0, 0.0)
    lines.append(f"  INS{inst_id}_FOV_REF_VECTOR   = ( {ref_vec[0]:.6f}, {ref_vec[1]:.6f}, {ref_vec[2]:.6f} )")

    if shape_str == "RECTANGLE" and fov_half_angle_cross_deg is not None:
        lines.append(f"  INS{inst_id}_FOV_CROSS_ANGLE  = {fov_half_angle_cross_deg}")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# SCLK — Spacecraft Clock Kernel
# ---------------------------------------------------------------------------

def generate_sclk(sc_id: int, mission_start: str, tick_rate_hz: float = 1.0) -> str:
    abs_id = abs(sc_id)

    lines = [
        "KPL/SCLK",
        "",
        "\\begintext",
        f"  Spacecraft clock kernel for NAIF ID {sc_id}",
        f"  Mission start: {mission_start}",
        f"  Tick rate: {tick_rate_hz} Hz",
        "",
        "\\begindata",
        "",
        f"  SCLK_KERNEL_ID           = ( @{mission_start} )",
        f"  SCLK_DATA_TYPE_{abs_id}  = ( 1 )",
        f"  SCLK01_TIME_SYSTEM_{abs_id} = ( 1 )",
        f"  SCLK01_N_FIELDS_{abs_id} = ( 2 )",
        f"  SCLK01_MODULI_{abs_id}   = ( 4294967296 {int(tick_rate_hz)} )",
        f"  SCLK01_OFFSETS_{abs_id}  = ( 0 0 )",
        f"  SCLK01_OUTPUT_DELIM_{abs_id} = ( 1 )",
        "",
        f"  SCLK_PARTITION_START_{abs_id} = ( 0.0000000000000E+00 )",
        f"  SCLK_PARTITION_END_{abs_id}   = ( 2.8147497671066E+14 )",
        "",
        f"  SCLK01_COEFFICIENTS_{abs_id} = (",
        f"    0.0000000000000E+00  @{mission_start}  {1.0 / tick_rate_hz:.16E}",
        f"  )",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# SPK — mkspk input (state table)
# ---------------------------------------------------------------------------

def _kepler_to_state(sma_km: float, ecc: float, inc_deg: float, raan_deg: float,
                     aop_deg: float, ta_deg: float, mu: float) -> tuple[
                         tuple[float, float, float], tuple[float, float, float]]:
    inc = math.radians(inc_deg)
    raan = math.radians(raan_deg)
    aop = math.radians(aop_deg)
    ta = math.radians(ta_deg)

    p = sma_km * (1 - ecc**2)
    r_mag = p / (1 + ecc * math.cos(ta))

    # Perifocal coordinates
    r_pf = (r_mag * math.cos(ta), r_mag * math.sin(ta), 0.0)
    v_coeff = math.sqrt(mu / p)
    v_pf = (-v_coeff * math.sin(ta), v_coeff * (ecc + math.cos(ta)), 0.0)

    # Rotation matrix perifocal -> inertial
    cos_o, sin_o = math.cos(raan), math.sin(raan)
    cos_w, sin_w = math.cos(aop), math.sin(aop)
    cos_i, sin_i = math.cos(inc), math.sin(inc)

    r11 = cos_o * cos_w - sin_o * sin_w * cos_i
    r12 = -cos_o * sin_w - sin_o * cos_w * cos_i
    r21 = sin_o * cos_w + cos_o * sin_w * cos_i
    r22 = -sin_o * sin_w + cos_o * cos_w * cos_i
    r31 = sin_w * sin_i
    r32 = cos_w * sin_i

    rx = r11 * r_pf[0] + r12 * r_pf[1]
    ry = r21 * r_pf[0] + r22 * r_pf[1]
    rz = r31 * r_pf[0] + r32 * r_pf[1]

    vx = r11 * v_pf[0] + r12 * v_pf[1]
    vy = r21 * v_pf[0] + r22 * v_pf[1]
    vz = r31 * v_pf[0] + r32 * v_pf[1]

    return (rx, ry, rz), (vx, vy, vz)


def generate_spk_comment(orbit_params: dict, epoch: str, sc_id: int = -100000,
                         central_body_id: int = 399, mu: float = 398600.4418,
                         n_points: int = 60) -> str:
    sma = orbit_params.get("sma_km", 6928.14)
    ecc = orbit_params.get("ecc", 0.001)
    inc = orbit_params.get("inc_deg", 97.6)
    raan = orbit_params.get("raan_deg", 0.0)
    aop = orbit_params.get("aop_deg", 0.0)

    period_s = 2 * math.pi * math.sqrt(sma**3 / mu)
    dt = period_s / n_points

    try:
        t0 = datetime.fromisoformat(epoch)
    except ValueError:
        t0 = datetime(2027, 6, 1, 12, 0, 0)

    header = [
        f"\\begincomment",
        f"  SPK input file for mkspk utility",
        f"  Object: {sc_id}  Center: {central_body_id}",
        f"  Epoch: {epoch}",
        f"  Orbit: SMA={sma} km, ECC={ecc}, INC={inc} deg",
        f"  Period: {period_s:.1f} s ({period_s/60:.1f} min)",
        f"  Reference frame: J2000",
        f"\\endcomment",
        "",
        "\\begindata",
        "",
        f"  INPUT_DATA_TYPE  = 'STATES'",
        f"  OUTPUT_SPK_TYPE  = 5",
        f"  OBJECT_ID        = {sc_id}",
        f"  CENTER_ID        = {central_body_id}",
        f"  REF_FRAME_NAME   = 'J2000'",
        f"  PRODUCER_ID      = 'BEPI'",
        f"  DATA_ORDER       = 'EPOCH X Y Z VX VY VZ'",
        f"  TIME_WRAPPER     = '# ETSECONDS'",
        f"  DATA_DELIMITER   = ','",
        f"  LINES_PER_RECORD = 1",
        f"  INPUT_DATA_UNITS = ( 'ANGLES = DEGREES' 'DISTANCES = km' )",
        "",
        "\\begintext",
        "",
    ]

    states = []
    for i in range(n_points + 1):
        ta_deg = (orbit_params.get("ta_deg", 0.0) + (360.0 * i / n_points)) % 360.0
        pos, vel = _kepler_to_state(sma, ecc, inc, raan, aop, ta_deg, mu)
        t = t0 + timedelta(seconds=dt * i)
        et = dt * i  # seconds past epoch
        states.append(f"  {et:.3f}, {pos[0]:.6f}, {pos[1]:.6f}, {pos[2]:.6f}, "
                      f"{vel[0]:.6f}, {vel[1]:.6f}, {vel[2]:.6f}")

    return "\n".join(header + states) + "\n"


# ---------------------------------------------------------------------------
# CK — msopck input (attitude)
# ---------------------------------------------------------------------------

def generate_ck_comment(attitude_mode: str, sc_id: int, mission_name: str = "BEPISAT",
                        epoch: str = "2027-06-01T12:00:00") -> str:
    frame_id = sc_id * 1000

    mode_desc = {
        "NADIR": "Nadir-pointing: +Z toward Earth center, +X along velocity",
        "INERTIAL": "Inertial hold: fixed attitude in J2000",
        "SUN_POINTING": "Sun-pointing: +X toward Sun, +Z normal to orbit plane",
    }
    desc = mode_desc.get(attitude_mode.upper(), f"Custom mode: {attitude_mode}")

    # Quaternion for each mode (identity for inertial, placeholder for others)
    if attitude_mode.upper() == "INERTIAL":
        q = (0.0, 0.0, 0.0, 1.0)
    elif attitude_mode.upper() == "NADIR":
        q = (0.0, 0.7071068, 0.0, 0.7071068)  # 90 deg about Y
    else:
        q = (0.7071068, 0.0, 0.0, 0.7071068)  # 90 deg about X

    lines = [
        f"\\begincomment",
        f"  CK input file for msopck utility",
        f"  Spacecraft: {mission_name} (NAIF ID {sc_id})",
        f"  Frame ID: {frame_id}",
        f"  Attitude mode: {desc}",
        f"  Epoch: {epoch}",
        f"\\endcomment",
        "",
        "\\begindata",
        "",
        f"  CK_TYPE           = 3",
        f"  INSTRUMENT_ID     = {frame_id}",
        f"  REFERENCE_FRAME   = 'J2000'",
        f"  CK_SEGMENT_ID     = '{mission_name}_ATT'",
        f"  SCLK_KERNEL_FILE  = '{mission_name.lower()}.tsc'",
        f"  LSK_FILE_NAME     = 'naif0012.tls'",
        f"  PRODUCER_ID       = 'BEPI'",
        f"  INPUT_DATA_TYPE   = 'QUATERNIONS'",
        f"  INPUT_TIME_TYPE   = 'UTC'",
        f"  QUATERNION_TYPE   = 'SPICE'",
        "",
        "\\begintext",
        "",
        f"  UTC_TIME  Q0  Q1  Q2  Q3  AV1  AV2  AV3",
    ]

    # Generate 10 sample attitude records (constant attitude)
    try:
        t0 = datetime.fromisoformat(epoch)
    except ValueError:
        t0 = datetime(2027, 6, 1, 12, 0, 0)

    for i in range(10):
        t = t0 + timedelta(minutes=i * 10)
        ts = t.strftime("%Y-%m-%dT%H:%M:%S")
        lines.append(f"  {ts}  {q[0]:.7f}  {q[1]:.7f}  {q[2]:.7f}  {q[3]:.7f}  0.0  0.0  0.0")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# PCK — Planetary Constants Kernel
# ---------------------------------------------------------------------------

def generate_pck(bodies: list[BodyDef] | None = None) -> str:
    if bodies is None:
        bodies = STANDARD_BODIES

    lines = [
        "KPL/PCK",
        "",
        "\\begintext",
        "  Planetary constants kernel generated by BEPI",
        f"  Generated: {datetime.utcnow().isoformat()}",
        "  Source: IAU 2015 report + DE440",
        "",
        "\\begindata",
        "",
    ]

    for b in bodies:
        lines += [
            f"  BODY{b.naif_id}_RADII     = ( {b.radii_km[0]:.4f}, {b.radii_km[1]:.4f}, {b.radii_km[2]:.4f} )",
            f"  BODY{b.naif_id}_POLE_RA   = ( {b.pole_ra_deg:.6f}   0.0   0.0 )",
            f"  BODY{b.naif_id}_POLE_DEC  = ( {b.pole_dec_deg:.6f}   0.0   0.0 )",
            f"  BODY{b.naif_id}_PM        = ( {b.pm_deg:.6f}   {b.pm_rate_deg_per_day:.10f}   0.0 )",
            "",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# MK — Meta-Kernel
# ---------------------------------------------------------------------------

def generate_mk(mission_name: str, kernel_files: list[str],
                kernel_dir: str = "kernels") -> str:
    lines = [
        "KPL/MK",
        "",
        "\\begintext",
        f"  Meta-kernel for {mission_name}",
        f"  Generated by BEPI on {datetime.utcnow().isoformat()}",
        "",
        "\\begindata",
        "",
        f"  PATH_VALUES  = ( '{kernel_dir}' )",
        f"  PATH_SYMBOLS = ( 'KERNELS' )",
        "",
        "  KERNELS_TO_LOAD = (",
    ]

    for kf in kernel_files:
        lines.append(f"    '$KERNELS/{kf}'")

    lines += [
        "  )",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# DSK — mkdsk input
# ---------------------------------------------------------------------------

def generate_dsk_input(body_name: str, shape: str = "ELLIPSOID",
                       radii_km: tuple[float, float, float] | None = None,
                       naif_id: int = 399) -> str:
    if radii_km is None:
        for b in STANDARD_BODIES:
            if b.name.upper() == body_name.upper():
                radii_km = b.radii_km
                naif_id = b.naif_id
                break
        else:
            radii_km = (100.0, 100.0, 100.0)

    lines = [
        f"\\begincomment",
        f"  DSK input for mkdsk utility",
        f"  Body: {body_name} (NAIF ID {naif_id})",
        f"  Shape: {shape}",
        f"  Radii: {radii_km[0]:.4f} x {radii_km[1]:.4f} x {radii_km[2]:.4f} km",
        f"\\endcomment",
        "",
        "\\begindata",
        "",
        f"  INPUT_SHAPE    = '{shape.upper()}'",
        f"  SURFACE_NAME   = '{body_name}_SURFACE'",
        f"  CENTER_NAME    = '{body_name}'",
        f"  REF_FRAME_NAME = 'IAU_{body_name.upper()}'",
        f"  START_TIME     = '2000-JAN-01'",
        f"  STOP_TIME      = '2100-JAN-01'",
        f"  DATA_CLASS     = 2",
        "",
    ]

    if shape.upper() == "ELLIPSOID":
        lines += [
            f"  A_RADIUS       = {radii_km[0]:.4f}",
            f"  B_RADIUS       = {radii_km[1]:.4f}",
            f"  C_RADIUS       = {radii_km[2]:.4f}",
            "",
        ]
    elif shape.upper() == "SPHERE":
        r = radii_km[0]
        lines += [
            f"  A_RADIUS       = {r:.4f}",
            f"  B_RADIUS       = {r:.4f}",
            f"  C_RADIUS       = {r:.4f}",
            "",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# generate_all_kernels
# ---------------------------------------------------------------------------

def generate_all_kernels(params: MissionKernelParams) -> dict[str, str]:
    name = params.mission_name
    sc_id = params.sc_naif_id
    kernels: dict[str, str] = {}

    # FK
    fk_file = f"{name.lower()}.tf"
    kernels[fk_file] = generate_fk(name, sc_id, params.sc_body_axes, params.instruments)

    # IK for each instrument
    for inst in params.instruments:
        ik_file = f"{name.lower()}_{inst.abbrev.lower()}.ti"
        kernels[ik_file] = generate_ik(
            f"{name}_{inst.abbrev}", inst.fov_shape, inst.fov_half_angle_deg,
            inst.boresight, sc_id, inst.naif_id_offset, inst.fov_half_angle_cross_deg,
        )

    # SCLK
    sclk_file = f"{name.lower()}.tsc"
    kernels[sclk_file] = generate_sclk(sc_id, params.mission_start, params.tick_rate_hz)

    # SPK (mkspk input)
    spk_file = f"{name.lower()}_spk.txt"
    orbit_dict = {
        "sma_km": params.orbit_sma_km,
        "ecc": params.orbit_ecc,
        "inc_deg": params.orbit_inc_deg,
        "raan_deg": params.orbit_raan_deg,
        "aop_deg": params.orbit_aop_deg,
        "ta_deg": params.orbit_ta_deg,
    }
    central_ids = {"EARTH": 399, "MOON": 301, "MARS": 499, "JUPITER": 599}
    center_id = central_ids.get(params.central_body.upper(), 399)
    kernels[spk_file] = generate_spk_comment(
        orbit_dict, params.epoch, sc_id, center_id, params.central_body_mu_km3s2,
    )

    # CK (msopck input)
    ck_file = f"{name.lower()}_ck.txt"
    kernels[ck_file] = generate_ck_comment(params.attitude_mode, sc_id, name, params.epoch)

    # PCK
    all_bodies = list(STANDARD_BODIES) + list(params.extra_bodies)
    pck_file = f"{name.lower()}.tpc"
    kernels[pck_file] = generate_pck(all_bodies)

    # DSK input for central body
    dsk_file = f"{name.lower()}_{params.central_body.lower()}_dsk.txt"
    kernels[dsk_file] = generate_dsk_input(params.central_body)

    # MK (meta-kernel) — references the generated text kernels
    loadable = [fk_file, sclk_file, pck_file]
    for inst in params.instruments:
        loadable.append(f"{name.lower()}_{inst.abbrev.lower()}.ti")
    mk_file = f"{name.lower()}.tm"
    kernels[mk_file] = generate_mk(name, loadable, params.kernel_dir)

    return kernels
