DRD_CATALOG = [
    {
        "code": "MRD",
        "title": "Mission Requirements Document",
        "review": "MDR",
        "ecss_source": "ECSS-E-ST-10-06C",
        "description": "Top-level mission needs, objectives, and derived system requirements",
    },
    {
        "code": "MCD",
        "title": "Mission Concept Document",
        "review": "MDR",
        "ecss_source": "ECSS-E-ST-10C",
        "description": "Mission concept description, operational scenarios, and feasibility assessment",
    },
    {
        "code": "SRD",
        "title": "System Requirements Document",
        "review": "PRR",
        "ecss_source": "ECSS-E-ST-10-06C",
        "description": "Complete set of traceable system requirements with verification methods assigned",
    },
    {
        "code": "SEP",
        "title": "System Engineering Plan",
        "review": "PRR",
        "ecss_source": "ECSS-E-ST-10C",
        "description": "System engineering approach, processes, tools, and interfaces for the project",
    },
    {
        "code": "PMP",
        "title": "Project Management Plan",
        "review": "PRR",
        "ecss_source": "ECSS-M-ST-10C",
        "description": "Project organization, WBS, schedule, cost baseline, and management approach",
    },
    {
        "code": "VCD",
        "title": "Verification Control Document",
        "review": "SRR",
        "ecss_source": "ECSS-E-ST-10-02C",
        "description": "Requirements traceability matrix linking each requirement to its verification method and status",
    },
    {
        "code": "ICD",
        "title": "Interface Control Document",
        "review": "SRR",
        "ecss_source": "ECSS-E-ST-10C",
        "description": "Definition of all mechanical, electrical, and functional interfaces between subsystems and external entities",
    },
    {
        "code": "RAR",
        "title": "Risk Assessment Report",
        "review": "SRR",
        "ecss_source": "ECSS-M-ST-80C",
        "description": "Identified risks with probability, severity, mitigation actions, and risk register",
    },
    {
        "code": "DDF",
        "title": "Design Definition File",
        "review": "PDR",
        "ecss_source": "ECSS-E-ST-10C",
        "description": "Compilation of design documents defining the spacecraft configuration, drawings, and specifications",
    },
    {
        "code": "BMR",
        "title": "Budget and Margin Report",
        "review": "PDR",
        "ecss_source": "ECSS-E-HB-10-02A",
        "description": "Mass, power, link, thermal, and delta-V budgets with margins at current design maturity",
    },
    {
        "code": "VP",
        "title": "Verification Plan",
        "review": "PDR",
        "ecss_source": "ECSS-E-ST-10-02C",
        "description": "Plan defining how all requirements will be verified, test levels, and campaign sequence",
    },
    {
        "code": "PA-PLAN",
        "title": "Product Assurance Plan",
        "review": "PDR",
        "ecss_source": "ECSS-Q-ST-10C",
        "description": "Plan for quality assurance, reliability, safety, EEE parts, and materials activities",
    },
    {
        "code": "MAIT-PLAN",
        "title": "MAIT Plan",
        "review": "PDR",
        "ecss_source": "ECSS-E-ST-10-03C",
        "description": "Manufacturing, Assembly, Integration, and Testing plan with sequence and facilities",
    },
    {
        "code": "TS",
        "title": "Test Specifications",
        "review": "CDR",
        "ecss_source": "ECSS-E-ST-10-03C",
        "description": "Detailed test procedures, pass/fail criteria, and instrumentation requirements for all test campaigns",
    },
    {
        "code": "AS-DOC",
        "title": "Analysis Summary Documents",
        "review": "CDR",
        "ecss_source": "ECSS-E-ST-10C",
        "description": "Summary of structural, thermal, EMC, link budget, and other engineering analyses",
    },
    {
        "code": "DJF",
        "title": "Design Justification File",
        "review": "CDR",
        "ecss_source": "ECSS-E-ST-10C",
        "description": "Evidence that the design meets all requirements, including trade studies and analysis reports",
    },
    {
        "code": "PPPL",
        "title": "Preferred Parts and Processes List",
        "review": "CDR",
        "ecss_source": "ECSS-Q-ST-60C",
        "description": "Approved list of EEE components, materials, and manufacturing processes for the project",
    },
    {
        "code": "FMECA-P",
        "title": "FMECA Report (preliminary)",
        "review": "PDR",
        "ecss_source": "ECSS-Q-ST-30-02C",
        "description": "Preliminary Failure Modes, Effects and Criticality Analysis identifying potential single-point failures early in design",
    },
    {
        "code": "FMECA",
        "title": "FMECA Report",
        "review": "CDR",
        "ecss_source": "ECSS-Q-ST-30-02C",
        "description": "Failure Modes, Effects and Criticality Analysis identifying single-point failures and critical items",
    },
    {
        "code": "QSR",
        "title": "Qualification Status Report",
        "review": "QR",
        "ecss_source": "ECSS-E-ST-10-02C",
        "description": "Summary of qualification test results demonstrating compliance with all requirements",
    },
    {
        "code": "TR",
        "title": "Test Reports",
        "review": "QR",
        "ecss_source": "ECSS-E-ST-10-03C",
        "description": "Formal reports for each completed test campaign including results, anomalies, and dispositions",
    },
    {
        "code": "NCR-LOG",
        "title": "Non-Conformance Report Log",
        "review": "QR",
        "ecss_source": "ECSS-Q-ST-20C",
        "description": "Registry of all non-conformances with disposition, waiver status, and closure evidence",
    },
    {
        "code": "ATR",
        "title": "Acceptance Test Report",
        "review": "AR",
        "ecss_source": "ECSS-E-ST-10-03C",
        "description": "Report of flight model acceptance test results confirming workmanship and performance",
    },
    {
        "code": "EIDP",
        "title": "End-Item Data Package",
        "review": "AR",
        "ecss_source": "ECSS-Q-ST-20C",
        "description": "Complete documentation package delivered with the flight model including as-built drawings and test history",
    },
    {
        "code": "OP",
        "title": "Operations Plan",
        "review": "ORR",
        "ecss_source": "ECSS-E-ST-10C",
        "description": "Plan for routine satellite operations including contact schedules, monitoring, and anomaly response",
    },
    {
        "code": "FOP",
        "title": "Flight Operations Procedures",
        "review": "ORR",
        "ecss_source": "ECSS-E-ST-10C",
        "description": "Step-by-step procedures for all nominal and contingency in-orbit operations",
    },
    {
        "code": "DP",
        "title": "Disposal Plan",
        "review": "ELR",
        "ecss_source": "ECSS-U-AS-10C",
        "description": "Approved plan for end-of-life passivation, deorbit or graveyard orbit manoeuvres",
    },
    {
        "code": "MCR-RP",
        "title": "Mission Close-out Report",
        "review": "MCR",
        "ecss_source": "ECSS-M-ST-10C",
        "description": "Final report summarising mission achievements, open items closure, and archiving status",
    },
    {
        "code": "LL",
        "title": "Lessons Learned Report",
        "review": "MCR",
        "ecss_source": "ECSS-M-ST-10C",
        "description": "Documented lessons learned from the mission for incorporation into future projects",
    },
]
