ECSS_STANDARDS = {
    "ECSS-M-ST-10C": {
        "id": "ECSS-M-ST-10C",
        "branch": "M",
        "title": "Project planning and implementation",
        "scope": "Requirements for project planning, scheduling, and work breakdown structure",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-m-st-10c-project-planning-and-implementation/",
    },
    "ECSS-M-ST-40C": {
        "id": "ECSS-M-ST-40C",
        "branch": "M",
        "title": "Configuration and information management",
        "scope": "Requirements for configuration management, documentation, and product data management",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-m-st-40c-configuration-and-information-management/",
    },
    "ECSS-M-ST-80C": {
        "id": "ECSS-M-ST-80C",
        "branch": "M",
        "title": "Risk management",
        "scope": "Requirements for systematic risk identification, analysis, mitigation, and monitoring",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-m-st-80c-risk-management/",
    },
    "ECSS-E-ST-10C": {
        "id": "ECSS-E-ST-10C",
        "branch": "E",
        "title": "System engineering general requirements",
        "scope": "System engineering process requirements applicable across all mission phases",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-e-st-10c-system-engineering-general-requirements/",
    },
    "ECSS-E-ST-10-02C": {
        "id": "ECSS-E-ST-10-02C",
        "branch": "E",
        "title": "Verification",
        "scope": "Requirements for the verification process including test, analysis, inspection, and review of design",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-e-st-10-02c-verification/",
    },
    "ECSS-E-ST-10-06C": {
        "id": "ECSS-E-ST-10-06C",
        "branch": "E",
        "title": "Technical requirements specification",
        "scope": "Requirements for writing clear, verifiable technical requirements",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-e-st-10-06c-technical-requirements-specification/",
    },
    "ECSS-E-HB-10-02A": {
        "id": "ECSS-E-HB-10-02A",
        "branch": "E",
        "title": "Verification guidelines",
        "scope": "Guidance on margin policy and budget management across mission phases",
        "subsystem": None,
        "url": "https://ecss.nl/hbstms/ecss-e-hb-10-02a-verification-guidelines-17-december-2010/",
    },
    "ECSS-E-ST-20C": {
        "id": "ECSS-E-ST-20C",
        "branch": "E",
        "title": "Electrical and electronic",
        "scope": "Requirements for spacecraft electrical power systems and harness design",
        "subsystem": "EPS",
        "url": "https://ecss.nl/standard/ecss-e-st-20c-electrical-and-electronic/",
    },
    "ECSS-E-ST-20-20C": {
        "id": "ECSS-E-ST-20-20C",
        "branch": "E",
        "title": "Electrical design and interface requirements for power supply",
        "scope": "Requirements for electrical interfaces of spacecraft power supply subsystems",
        "subsystem": "EPS",
        "url": "https://ecss.nl/standard/ecss-e-st-20-20c-electrical-design-and-interface-requirements-for-power-supply/",
    },
    "ECSS-E-ST-31C": {
        "id": "ECSS-E-ST-31C",
        "branch": "E",
        "title": "Thermal control general requirements",
        "scope": "Requirements for spacecraft thermal control design, analysis, and verification",
        "subsystem": "TCS",
        "url": "https://ecss.nl/standard/ecss-e-st-31c-thermal-control-general-requirements/",
    },
    "ECSS-E-ST-32C": {
        "id": "ECSS-E-ST-32C",
        "branch": "E",
        "title": "Structural general requirements",
        "scope": "Requirements for structural design, analysis, and verification of spacecraft structures",
        "subsystem": "STR",
        "url": "https://ecss.nl/standard/ecss-e-st-32c-structural-general-requirements/",
    },
    "ECSS-E-HB-32-26A": {
        "id": "ECSS-E-HB-32-26A",
        "branch": "E",
        "title": "Spacecraft mechanical loads analysis handbook",
        "scope": "Guidance on spacecraft structural loads analysis methods and margin philosophy",
        "subsystem": "STR",
        "url": "https://ecss.nl/hbstms/ecss-e-hb-32-26a-spacecraft-mechanical-loads-analysis-handbook/",
    },
    "ECSS-E-ST-33-01C": {
        "id": "ECSS-E-ST-33-01C",
        "branch": "E",
        "title": "Mechanisms",
        "scope": "Requirements for design, analysis, testing and qualification of spacecraft mechanisms",
        "subsystem": "MECH",
        "url": "https://ecss.nl/standard/ecss-e-st-33-01c-mechanisms/",
    },
    "ECSS-E-ST-35C": {
        "id": "ECSS-E-ST-35C",
        "branch": "E",
        "title": "Propulsion general requirements",
        "scope": "Requirements for spacecraft propulsion systems design, manufacture, and verification",
        "subsystem": "PROP",
        "url": "https://ecss.nl/standard/ecss-e-st-35c-propulsion-general-requirements/",
    },
    "ECSS-E-ST-40C": {
        "id": "ECSS-E-ST-40C",
        "branch": "E",
        "title": "Software general requirements",
        "scope": "Requirements for on-board and ground software development lifecycle",
        "subsystem": "SW",
        "url": "https://ecss.nl/standard/ecss-e-st-40c-software-general-requirements/",
    },
    "ECSS-E-ST-50C": {
        "id": "ECSS-E-ST-50C",
        "branch": "E",
        "title": "Communications general requirements",
        "scope": "Requirements for spacecraft RF and optical communication systems",
        "subsystem": "COM",
        "url": "https://ecss.nl/standard/ecss-e-st-50c-communications-general-requirements/",
    },
    "ECSS-E-ST-60-10C": {
        "id": "ECSS-E-ST-60-10C",
        "branch": "E",
        "title": "Control systems general requirements",
        "scope": "Requirements for AOCS and other spacecraft control system design and verification",
        "subsystem": "AOCS",
        "url": "https://ecss.nl/standard/ecss-e-st-60-10c-control-systems-general-requirements/",
    },
    "ECSS-Q-ST-10C": {
        "id": "ECSS-Q-ST-10C",
        "branch": "Q",
        "title": "Product assurance management",
        "scope": "Requirements for product assurance programme, planning, and implementation",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-q-st-10c-product-assurance-management/",
    },
    "ECSS-Q-ST-20C": {
        "id": "ECSS-Q-ST-20C",
        "branch": "Q",
        "title": "Quality assurance",
        "scope": "Requirements for quality management system, manufacturing, and inspection",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-q-st-20c-quality-assurance/",
    },
    "ECSS-Q-ST-30C": {
        "id": "ECSS-Q-ST-30C",
        "branch": "Q",
        "title": "Dependability",
        "scope": "Requirements for reliability, availability, maintainability and safety analyses",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-q-st-30c-dependability/",
    },
    "ECSS-Q-ST-40C": {
        "id": "ECSS-Q-ST-40C",
        "branch": "Q",
        "title": "Safety",
        "scope": "Requirements for hazard identification, safety analysis, and safety verification",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-q-st-40c-safety/",
    },
    "ECSS-Q-ST-60C": {
        "id": "ECSS-Q-ST-60C",
        "branch": "Q",
        "title": "Electrical, electronic, and electromechanical (EEE) components",
        "scope": "Requirements for selection, procurement, screening, and qualification of EEE parts",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-q-st-60c-electrical-electronic-and-electromechanical-eee-components/",
    },
    "ECSS-Q-ST-70C": {
        "id": "ECSS-Q-ST-70C",
        "branch": "Q",
        "title": "Materials, mechanical parts and processes",
        "scope": "Requirements for selection and qualification of materials and mechanical parts for space use",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-q-st-70c-materials-mechanical-parts-and-processes/",
    },
    "ECSS-Q-ST-80C": {
        "id": "ECSS-Q-ST-80C",
        "branch": "Q",
        "title": "Software product assurance",
        "scope": "Product assurance requirements for flight and critical ground software",
        "subsystem": "SW",
        "url": "https://ecss.nl/standard/ecss-q-st-80c-software-product-assurance/",
    },
    "ECSS-U-AS-10C": {
        "id": "ECSS-U-AS-10C",
        "branch": "U",
        "title": "Space debris mitigation",
        "scope": "Requirements for limiting the generation of orbital debris and ensuring compliant disposal",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-u-as-10c-space-debris-mitigation/",
    },
    "ECSS-M-ST-60C": {
        "id": "ECSS-M-ST-60C",
        "branch": "M",
        "title": "Cost and schedule management",
        "scope": "Requirements for cost estimation, earned value management, and schedule control",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-m-st-60c-cost-and-schedule-management/",
    },
    "ECSS-E-ST-10-03C": {
        "id": "ECSS-E-ST-10-03C",
        "branch": "E",
        "title": "Testing",
        "scope": "Requirements for test planning, execution, and reporting across all levels of assembly",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-e-st-10-03c-testing/",
    },
    "ECSS-E-ST-10-04C": {
        "id": "ECSS-E-ST-10-04C",
        "branch": "E",
        "title": "Space environment",
        "scope": "Definition of the natural space environment for use in spacecraft design and analysis",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-e-st-10-04c-space-environment/",
    },
    "ECSS-Q-ST-30-02C": {
        "id": "ECSS-Q-ST-30-02C",
        "branch": "Q",
        "title": "Failure modes, effects (and criticality) analysis (FMEA/FMECA)",
        "scope": "Requirements for conducting FMEA and FMECA at system and subsystem level",
        "subsystem": None,
        "url": "https://ecss.nl/standard/ecss-q-st-30-02c-failure-modes-effects-and-criticality-analysis-fmea-fmeca/",
    },
    "ECSS-E-ST-20-08C": {
        "id": "ECSS-E-ST-20-08C",
        "branch": "E",
        "title": "Photovoltaic assemblies and components",
        "scope": "Requirements for design, manufacture, and testing of solar cell assemblies for spacecraft",
        "subsystem": "EPS",
        "url": "https://ecss.nl/standard/ecss-e-st-20-08c-photovoltaic-assemblies-and-components/",
    },
}
