SUBSYSTEM_DEFINITIONS = {
    "STR": {
        "name": "Structure",
        "full_name": "Structural Subsystem",
        "ecss_standards": ["ECSS-E-ST-32C", "ECSS-E-HB-32-26A"],
        "primary_budgets": ["mass_kg", "cost_eur"],
        "description": "Primary and secondary structure, brackets, inserts",
    },
    "TCS": {
        "name": "Thermal",
        "full_name": "Thermal Control Subsystem",
        "ecss_standards": ["ECSS-E-ST-31C"],
        "primary_budgets": ["mass_kg", "power_w", "dissipation_w", "cost_eur"],
        "description": "MLI, heaters, radiators, heat pipes, louvers",
    },
    "EPS": {
        "name": "Power",
        "full_name": "Electrical Power Subsystem",
        "ecss_standards": ["ECSS-E-ST-20C", "ECSS-E-ST-20-20C"],
        "primary_budgets": ["mass_kg", "power_w", "cost_eur"],
        "description": "Solar arrays, batteries, PCDU, harness distribution",
    },
    "AOCS": {
        "name": "AOCS",
        "full_name": "Attitude and Orbit Control Subsystem",
        "ecss_standards": ["ECSS-E-ST-60-10C"],
        "primary_budgets": ["mass_kg", "power_w", "delta_v_ms", "cost_eur"],
        "description": "Sensors (star trackers, sun sensors, gyros), actuators (reaction wheels, thrusters, magnetorquers)",
    },
    "PROP": {
        "name": "Propulsion",
        "full_name": "Propulsion Subsystem",
        "ecss_standards": ["ECSS-E-ST-35C"],
        "primary_budgets": ["mass_kg", "delta_v_ms", "cost_eur"],
        "description": "Thrusters, tanks, feed system, propellant",
    },
    "COM": {
        "name": "Communications",
        "full_name": "Communications Subsystem",
        "ecss_standards": ["ECSS-E-ST-50C"],
        "primary_budgets": ["mass_kg", "power_w", "data_rate_kbps", "cost_eur"],
        "description": "Transponders, antennas, RF distribution",
    },
    "CDH": {
        "name": "Data Handling",
        "full_name": "Command and Data Handling Subsystem",
        "ecss_standards": ["ECSS-E-ST-50C"],
        "primary_budgets": ["mass_kg", "power_w", "data_rate_kbps", "cost_eur"],
        "description": "OBC, mass memory, remote terminal units",
    },
    "MECH": {
        "name": "Mechanisms",
        "full_name": "Mechanisms Subsystem",
        "ecss_standards": ["ECSS-E-ST-33-01C"],
        "primary_budgets": ["mass_kg", "cost_eur"],
        "description": "Deployment mechanisms, solar array drives, antenna pointing, separation systems",
    },
    "PL": {
        "name": "Payload",
        "full_name": "Payload",
        "ecss_standards": [],
        "primary_budgets": ["mass_kg", "power_w", "data_rate_kbps", "volume_cm3", "cost_eur"],
        "description": "Mission-specific instruments and equipment",
    },
    "HRN": {
        "name": "Harness",
        "full_name": "Electrical Harness",
        "ecss_standards": ["ECSS-E-ST-20C"],
        "primary_budgets": ["mass_kg", "cost_eur"],
        "description": "Cable harness, connectors",
    },
    "SW": {
        "name": "Software",
        "full_name": "On-Board Software",
        "ecss_standards": ["ECSS-E-ST-40C", "ECSS-Q-ST-80C"],
        "primary_budgets": ["cost_eur", "cost_nre_eur"],
        "description": "Flight software, FDIR, application SW",
    },
}
